### PR TITLE
Issue/5 design a better 404 page

### LINKED ISSUE #5: Design a better 404 page

### PR DESCRIPTION
**Pull request by micahalcorn**
This resolves #5 as directed by Aure in #design on Discord.
(I can no longer deep link to a message 😥)

**Note**

This design does not support right-to-left languages.

**Assumption**

Telegram button with be rendered in an alert rather than potentially below the fold.

### CODE REVIEW

**Comment by wanderingstan** [comment]
merged to `master` and deployed.

**Comment by joshfraser** [comment]
This breaks the dudes on the partners page & miniaturizes them.

@micahalcorn please be more careful that we don't break stuff with new commits.
@wanderingstan please be more careful while reviewing pull requests that they don't break stuff.

**Comment by wanderingstan** [comment]
@joshfraser We caught the mini-dudes shortly after merging this PR on Feb 21 and fixed it in commit 43e91e00f0c5a3625b84fa28a6935508c6125e31 . 

I think the confusion was that this PR didn't get closed. I finally marked as such today.

**Comment by joshfraser** [comment]
ah cool, sorry I'm behind on the conversation. been trying to get caught up on these pull requests.

**Comment by wanderingstan** [comment]
We did figure out that the reason these PRs weren't getting automatically closed: The PR was to `develop` and then I merged it directly to `master`. So...lesson learned. :)

**Pull request closed without merging**
