### PR TITLE
Move PB & WP to S3

### PR DESCRIPTION
**Pull request by ryana**
So heroku can stop serving these static files

### CODE REVIEW

**Comment by joshfraser** [comment]
I'd vote for setting up Cloudfront instead and serving all our static files from the CDN instead of just the PB & WP. Don't want to have a separate repo to update when those files change.

**Comment by ryana** [comment]
Yup totally. We'll fix it up with a proper asset -> CDN solution. Just needed to fix the site asap because response times were up over 10s due to all the assets we were asking the heroku router to serve.

**Comment by joshfraser** [comment]
Got it. Stan just gave me the update. Sorry, didn't have full context.

**Comment by ryana** [comment]
No worries at all. Knowing where the white paper / product brief is getting linked to is important! I would have asked the same questions!

**Comment by ryana** [comment]
https://github.com/libwilliam/flask-cdn hasn't been committed to in a year but looks like our best option

**Pull request merged**
