### PR TITLE
Partners page

### PR DESCRIPTION
**Pull request by micahalcorn**
Here is a first stab at the partners page. I have several questions/comments:

[According to @joshfraser](https://originprotocol.slack.com/archives/C72PD95H9/p1517603347000514), this page will replace  /build-on-origin.

1) Should the URL path change to something like /partners, or keep it the same for SEO continuity?
2) Does there need to be a nav link for this page?
3) I tried to create this branch from `develop`, but some past hotfixes to `master` were necessary to have in this branch. Should I be branching from `develop` and how should I deal with differences between `develop` and `master` when, for example, `style.css` is different in all three branches?
4) 10538a55a21a98587cdaa99fb8b6ce489ab742b3 updates FontAwesome to a newer version, which seems to have been necessary to get some icons that I needed. Is that alright? I believe that nothing is broken as a result. But should that update have been its own commit?
5) I noticed that the form styles on the existing build-on-origin page (and my update) do not match the email form on the landing page nor Aure's designs. I can update those in a future commit.
6) The existing build-on-origin had no rtl language support. I have not yet added that, but will in a future commit.
7) Is there a good way for me to test locally to see that the form has not been broken?
8) I believe that there are no translations for this page unless I failed to connect them correctly.
9) I think I saw some mention of a possible future design/development environment to run alongside the staging environment. It might be good to have something like that if there is not already so that I can get real-world feedback from Aure before you merge and deploy to staging.

### CODE REVIEW

**Comment by wanderingstan** [comment]
> 3. I tried to create this branch from develop, but some past hotfixes to master were necessary to have in this branch. Should I be branching from develop and how should I deal with differences between develop and master when, for example, style.css is different in all three branches?

My bad on `develop` falling behind--now updated. I'd actually say we should develop this in a `topic/partners-page` branch. Also fine to just point us to branches in your fork in mean time. Sound good?

> 4. 10538a5 updates FontAwesome to a newer version, which seems to have been necessary to get some icons that I needed. Is that alright? I believe that nothing is broken as a result. But should that update have been its own commit?

New versions always good. I'll check it from a security standpoint is all. 

> 5. I noticed that the form styles on the existing build-on-origin page (and my update) do not match the email form on the landing page nor Aure's designs. I can update those in a future commit.

Awesome. 

> 6. The existing build-on-origin had no rtl language support. I have not yet added that, but will in a future commit.

Good eye. 

> 7. Is there a good way for me to test locally to see that the form has not been broken?

Not at this time; no way to test the emails actually send. This may be a good time for us to set up a testing version of sendgrid. I hope this isn't a blocker right away. We can always test on staging. 

> 8. I believe that there are no translations for this page unless I failed to connect them correctly.

Nope. Just be sure all English is wrapped in `gettext()` so that babel-extract can find them. `translations/README.md` has docs on how to do the extraction and update the `messages.pot` file. I can walk you through that, and even getting that up into Google's translation tool to get first-pass machine translation. (I'd love to have someone else able to do that..it's kind of tedius. ;) )

Then we'll have to ping the gracious people in slack `#translation` channel to help with any new text. :)

> 9. I think I saw some mention of a possible future design/development environment to run alongside the staging environment. It might be good to have something like that if there is not already so that I can get real-world feedback from Aure before you merge and deploy to staging.

For sure. But really, the best (and fastest) thing would be for you to create your own free Heroku instance and deploy there. The free app is more than enough for testing. It will give you a crazy looking domain with `herokuapp` in it, but that's fine for testing and designer feedback. I can walk you through that too. 

You'll need to 
- Install heroku command line tools: https://devcenter.heroku.com/articles/heroku-cli
- Add heroku as remote: https://devcenter.heroku.com/articles/git
- Push your dev branch as to master on heroku (it only deploys from master): https://stackoverflow.com/a/8123465/59913

So great to have you helping out!

**Comment by micahalcorn** [comment]
@wanderingstan great, that all makes sense. Is it appropriate for me to...

a) close this PR
b) delete my branch and create a topic branch from `develop`
c) create a new PR when everything is ready to go

I generally know how to `git` but have never actually collaborated on a team with multiple branches and forks. 🙉

**Comment by wanderingstan** [comment]
Totally. 

You could also just rename your branch to `topic/partners-page` or `issue/79_partners_page` or similar, and then do PR to `develop` when its in good shape. (I.e. doesn't matter what you name things in your fork.)

We're still figuring out our git flow here as well!

**Comment by micahalcorn** [comment]
[We are abandoning the social icons on the partners page](https://originprotocol.slack.com/archives/C72PD95H9/p1517707467000072), so I will rollback the FontAwesome update. I don't think that it makes sense to update it on this branch and unnecessarily risk some consequences.

**Comment by micahalcorn** [comment]
Closing in favor of #85

**Pull request closed without merging**
