### PR TITLE
Add and remove contributors

### PR DESCRIPTION
**Pull request by micahalcorn**
As requested by @coleman415 and @matthewliu, this adds several contributor bios to the team page and removes a couple. As mentioned in Discord, the phrase "full stack developer" is a bit overused. I'm also not sure if there should be some logic to the order in which contributors are listed. Feel free to modify or request additional changes.

### CODE REVIEW

**Comment by micahalcorn** [comment]
For some reason, the headshots did not survive my commit. Let me investigate this before merging.

**Comment by micahalcorn** [comment]
@Gzing how do I add files to `flask-assets`/`flask-cdn` now that [we are now ignoring the `/static` directory](https://github.com/OriginProtocol/company-website/commit/3830b780ce19558a55503d9902bddf07feefdaa4).

**Comment by Gzing** [comment]
@micahalcorn not sure why the whole `static` directory is gitignored. You just add files like you always did in the `static` directory, nothing changes on that front.
Would it be possible for you to remove that from gitignore and add these instead:
```
static/.webassets-cache
static/gen
```
You should be able to commit your static content after the above changes.

Let me know if you want me to make a separate PR for this.

**Comment by micahalcorn** [comment]
I have added the missing files and updated the `.gitignore` as suggested by @Gzing and cleared with @wanderingstan.

**Comment by joshfraser** [comment]
Should have caught this before merging, but the filesize on these headshots is a bit out of control.

**Pull request merged**
