### PR TITLE
Investors via andrewhyde

### PR DESCRIPTION
**Pull request by micahalcorn**
This is a consolidation of three branches and PRs #182, #183, and #189.

This branch is currently deployed to https://originprotocol-com-micah.herokuapp.com/en/team for review. I would recommend getting versions of some of the logos without white backgrounds so that they don't bleed into the grey background of the page. We could have Aure take a pass at improving the logo sizing and quality if necessary.

The investors have been rearranged per @matthewliu.

Additional revisions have been included per @jonhearty.

### CODE REVIEW

**Comment by DanielVF** [comment]
Is there too much whitespace currently between the team members and the investors?

image

**Comment by micahalcorn** [comment]
@DanielVF good question. I assumed that was intentional (in the existing `master`) so that the investors appear on a different white triangle section. We could certainly raise the end of the advisor team section.

**Comment by micahalcorn** [comment]
@andrewhyde @matthewliu @joshfraser this is ready for your review and approval at https://originprotocol-com-micah.herokuapp.com/en/team.

**Comment by joshfraser** [comment]
Can we use transparent backgrounds on the logos (especially hashed and FBG). The background bleeds onto the grey.

Can we use real photos / find better images for Gil, Kamal & Garry?

**Comment by micahalcorn** [comment]
@joshfraser I've changed out some of the logos and improved the markup. @jonhearty suggested moving forward without those three individuals and we can add them once we get better photos. If that works, it's ready to review.

https://originprotocol-com-micah.herokuapp.com/en/team

**Comment by joshfraser** [comment]
These are all public figures. Should take 2 minutes to find alternative pictures that we can use.

**Comment by micahalcorn** [comment]
@joshfraser I didn't know if the images were provided/approved by the investor or where they were coming from. I've sourced those three to match what they use on LinkedIn.

Updated: https://originprotocol-com-micah.herokuapp.com/en/team

**Comment by joshfraser** [comment]
Agree with @DanielVF that we can get rid of that extra whitespace, but merging what we have for now.

**Pull request merged**
