### PR TITLE
Finish #46 and update README

### PR DESCRIPTION
**Pull request by ryana**
- Made the decorator conditional in tasks.py
- Made the call to `delay` predicated on the presence of a REDIS_URL
- Updated README to reflect how to run app with Heroku CLI

### CODE REVIEW

**Comment by wanderingstan** [comment]
Hey @ryana sorry I missed this. @joshfraser was just asking about `delay` today. Think we're still good to go on this one?

**Comment by ryana** [comment]
No prob. It seems to have a merge conflict now, so I'm happy to go resolve that tomorrow.

To be clear though: the `delay` is currently deployed to production. The purpose of this PR was to clean up the README and work towards making it so that the app behaved better locally.

**Comment by ryana** [comment]
@wanderingstan I'm honestly not sure. With all the activity lately I've lost track of where things stand with respect to this. I think the safe bet is to not merge it, close it, and then regroup this week.

**Comment by DanielVF** [comment]
Yes @ryana, I'm closing this one - it's two months old.

**Pull request closed without merging**
