### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by DanielVF**
Why Python 3 compatibility? Why not?

### CODE REVIEW

**Comment by wanderingstan** [comment]
I missed this PR come in. Fantastic--we really should move to py 3. Will review and test more tomorrow. Thanks!

**Comment by wanderingstan** [comment]
@DanielVF is this PR to indented to be a move to Python3, or just updating our coding style to be ready for the eventual move? 
I see `runtime.txt` was not updated, thus the question.

**Comment by DanielVF** [comment]
This was just intended to make the code able to run on both Python 2 and Python 3.  I wasn't actually flipping the runtime.

**Comment by joshfraser** [comment]
I'm okay if we decide to move to Python 3, but not excited about maintaining support for 2 versions of Python for something that only we use.

**Comment by DanielVF** [comment]
I agree with you on not having two supported platforms. 

I think we should move to Python 3 now since Python 2 goes end-of-life in less then two years, and switching now is essentially.

**Comment by DanielVF** [comment]
Python 3 not a priority on the website at this time.

**Pull request closed without merging**
