### PR TITLE
Run autopep8 on python files.

### PR DESCRIPTION
**Pull request by hucares**
Diffs are a result of running `autopep8 -r --in-place --aggressive --aggressive .`. This is to ensure that code conforms to the [PEP8](https://www.python.org/dev/peps/pep-0008/) standard. We should consider adding a python linter to a pre-commit hook.

### Test Plan
- [x] Check that site renders
- [x] Check that internationalization still works
- [x] Check that presale leads still persist to DB

### CODE REVIEW

**Comment by wanderingstan** [comment]
Thanks for this @hucares . As this touches literally every line, it may take us a while to get around to reviewing it. Thanks for your patience.

**Comment by joshfraser** [comment]
Alex, as a bit of feedback, it's best to build consensus with the team before sending a pull request like this. Not saying it's a bad idea, but everyone needs to be bought in and agreed on the style guide we want to use. Leaving this open for now, but we'll have some discussion before merging.

**Comment by Gzing** [comment]
Hey @hucares, thanks for the effort on this branch, I also care a lot about the repo adhering to PEP8 standards.
Just one suggestion:
Since this is out of sync and has merge conflicts, I was thinking maybe instead of doing a rebase with master, we just go ahead with a pre-commit hook which uses autopep8 (ex. https://github.com/chibiegg/git-autopep8)

This would cut the scope of this branch and introduce no changes to the files as of now. 
Going forward, the precommit hook will make sure that contributors conform to PEP8 standard and slowly autopep8 only the files they have interacted within a commit.

**Comment by DanielVF** [comment]
I agree with you that we should eventually do our python formatting at a part of checking in our code, rather than this big PR.

Thanks for the link to the script!

I'm going to close this now.

**Pull request closed without merging**
