### PR TITLE
fixes #137 by unifying email subscriptions on EmailList table

### LINKED ISSUE #137: Track unsubscribes in a single table
We currently pull from 3 different mailing lists when we send out our newsletter.

Unsubscribes are only supported on our official email list, but a lot of people filled out the presale form instead. We should add unsubscribed email address to a single table to unsubscribe you regardless of which mailing list you joined (and have a universal check before sending emails).

### PR DESCRIPTION
**Pull request by Gzing**
Single `EmailList` to send the newsletters now.
Includes a one time migration of emails from `Presale` and `Interest`  to `EmailList` table.
Going forward,  any `Presale` or `Interest` created would also create an `EmailList` object asynchronously.

### CODE REVIEW

**Comment by joshfraser** [comment]
Trying to get this merged in before sending out our monthly newsletter, but getting these errors. Any ideas what's up?

/Users/joshfraser/.virtualenvs/company-website/lib/python2.7/site-packages/sqlalchemy/orm/session.py:2253: SAWarning: Usage of the 'Session.add()' operation is not currently supported within the execution stage of the flush process. Results may not be consistent.  Consider using alternative event listeners or connection-level operations instead.
  % method)
/Users/joshfraser/.virtualenvs/company-website/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py:74: SAWarning: An exception has occurred during handling of a previous exception.  The previous exception is:
 <class 'sqlalchemy.exc.ResourceClosedError'> This transaction is closed

  "is:\n %s %s\n" % (self._exc_info[0], self._exc_info[1]))

**Comment by Gzing** [comment]
checking this, I see some merge conflicts as well. Will fix and update shortly

**Comment by joshfraser** [comment]
The merge conflict seems minor. It's the other issues that have me stumped. 

Never used those event listeners before, but looks like a neat way to do it.

**Comment by Gzing** [comment]
@joshfraser I have been trying to replicate the issue but it seems to be working fine for me.
Do you have specific steps that I should follow to reach that error?

**Comment by joshfraser** [comment]
Yeah it blows up when I fill out and submit the presale form

**Comment by joshfraser** [comment]
Ah, that was it. Thanks for your help debugging. We should probably update the README with better documentation on how to run the celery stuff locally.

**Pull request merged**
